### ISSUE TITLE
Support ipython password & https for notebooks

### ISSUE THREAD

**Issue by sdague** [tkf/emacs-ipython-notebook#144]
If you set a password and/or certificate file on the ipython notebook server ein mode fails with:

ein: [error] Error (parse-error) while opening notebook list at the server 

This means you can't use ein with cloud servers for your ipython notebook servers. Would be awesome if you could.

**Comment by reconmaster** [comment]
I thought I had this issue too, but then using the ein:notbooklist-login removed the connection refused issue. I am now getting the parse-error, but I think this is due to the incompatibility between ein and ipython 2.0 due to it changing the return to html rather than json. It looks like this known, but not yet rectified.

https://github.com/tkf/emacs-ipython-notebook/issues/133
