### ISSUE TITLE
ein:console-open freezes hangs Emacs

### ISSUE THREAD

**Issue by maximsch2** [tkf/emacs-ipython-notebook#92]
I am using EIN to work with a notebook started on the remote server. I am using ssh to forward the port to the local machine like this:

```
ssh -N -f -L 7000:127.0.0.1:7000 server.org
```

and then point EIN to local port 7000

I've tried to open IPython console using ein:console-open, but it seem to freeze Emacs (Emacs loads 1 core to 100%, but nothing happens after several minutes and emacs is not responding to other commands).

I am on OS X 10.7, ipython version on server is 0.13, emacs version is 24.2, EIN is latests version from git.

**Comment by tkf** [comment]
I wonder why it hangs Emacs.  But anyway, you need to setup ein:console-security-dir and ein:console-args to use it over ssh.

The simplest setting will be something like this:

``` cl
(setq ein:console-security-dir
      (expand-file-name "~/servers/SERVER/.config/ipython/profile_PROFILE_NAME/security"))
(setq ein:console-args "--ssh SERVER")
```

You will need to setup security directory (ein:console-security-dir) accessible from your local machine.  To do that, you can use sshfs:

```
sshfs SERVER:/home/YOU ~/servers/SERVER
```

Probably you need to use `.ipython/` instead of `.config/ipython/`.  Also, replace `PROFILE_NAME` with the profile you are using (such as `default`).

**Comment by tkf** [comment]
BTW, technically I can get rid of `ein:console-security-dir` but I am too lazy to implement that.  So until then please use sshfs.

**Comment by tkf** [comment]
See also:
- http://ipython.org/ipython-doc/dev/interactive/qtconsole.html#multiple-consoles
- http://ipython.org/ipython-doc/dev/config/overview.html?highlight=security%20directory#security-files
- http://ipython.org/ipython-doc/dev/parallel/parallel_security.html

**Comment by maximsch2** [comment]
Can you emulate IPython console using scratch notebook to avoid doing all
the setup?

Maxim Grechkin

**Comment by tkf** [comment]
Depends on what you expect for console.  By default, it just opens a worksheet which you don't need to save.  You can enable `ein:pseudo-console-mode` to make it more close to console.  But currently it just make it possible to use RET to execute a cell.

I use `ein:console-open` only for debugging, because it works well with python.el's ipdb support.  As IPython notebook server does not support debugging feature yet, so there is nothing I can do in EIN for now.
